version: 0.2

phases:
  install: 
    runtime-versions:
      golang: 1.18
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:
      - cd deploy-app-aws-ecs/base-app/server
      - golint -set_exit_status
      - go test -v

artifacts:
  files:
    - buildspec.yml