apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: vpa
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: demo-app
        image: yvesdeffo/demo-app:v1
        resources:
          requests:
            memory: "263Mi"
            cpu: "200m"
          limits:
            memory: "263Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: vpa
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: demo-app
