apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: demo-app
        image: yvesdenis/demo-app:v1
        env:
        - name: BROKER_URL
          value: "tcp://activemq:61616"
        - name: BROKER_USER
          value: "admin"
        - name: BROKER_PWD
          value: "admin"
        - name: BROKER_QUEUE_NAME
          value: "demo"
        resources:
          requests:
            memory: "263Mi"
            cpu: "200m"
          limits:
            memory: "263Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: demo-app
