version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:=latest}
      - IMAGE_REPO_CREATE_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_CREATE
      - IMAGE_REPO_GET_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_GET
      - IMAGE_REPO_DELETE_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_DELETE
  build:
    commands:
      - echo Build started on `date`
      - echo Moving into serverless-system folder... 
      - cd ./serverless-system         
      - echo Building serverless resources... 
      - sam build --parameter-overrides TagVersion=$IMAGE_TAG --parallel
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging serverless resources...
      - sam package --region $AWS_DEFAULT_REGION --output-template-file packaged-template.yaml --image-repositories CreateOrderFunction=$IMAGE_REPO_CREATE_URL --image-repositories GetOrderFunction=$IMAGE_REPO_GET_URL --image-repositories DeleteOrderFunction=$IMAGE_REPO_DELETE_URL --resolve-s3   
artifacts:
  files:
    - serverless-system/*