AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for local test

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: MyLambdaRequestAuthorizer
        Authorizers:
          MyLambdaRequestAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt MyAuthFunction.Arn
            Identity:
              Headers:
                - AUTH

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: test_order
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders
            Method: get

  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../
      Handler: auth.handler
      Runtime: go1.x
      Architectures:
          - x86_64