name: IAC codepipeline - codebuild
on:
  push:
      branches: [ "serverless-system" ]

env:
  AWS_REGION: ca-central-1 
  ASSUME_ROLE: arn:aws:iam::516193157210:role/base-app-role

permissions:
  id-token: write
  contents: read

jobs:
  iac-deploy:
    name: IAC Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Download project dependencies
        run: cd ./serverless-system/iac-pulumi && go mod download
      - name: Run Pulumi unit tests
        run: cd ./serverless-system/iac-pulumi && go test -v .
      - name: Displays a preview of the updates to the existing stack
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: blog-projects/iac-codepipeline/prod
          color: always
          work-dir: serverless-system/iac-pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
      - name: Create or update the resources in a stack
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: blog-projects/iac-codepipeline/prod
          color: always
          work-dir: serverless-system/iac-pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
      